### ISSUE TITLE
Not detecting root perms

### ISSUE THREAD

**Issue by milindgoel15** [TacoTheDank/Scoop#1]
Using latest version from releases tab, it doesn't detect root perms even after successfully granting root.
![Screenshot_20210213-213018062](https://user-images.githubusercontent.com/45682747/107854588-d37ccb00-6e42-11eb-9e57-40a1ad2d4b59.jpg)
![Screenshot_20210213-213003096](https://user-images.githubusercontent.com/45682747/107854590-d5468e80-6e42-11eb-951a-b9a294e79085.jpg)

Rom- evox a10
Magisk- 21.4 stable

**Comment by X1nto** [comment]
will be fixed with #2

**Comment by milindgoel15** [comment]
Ikr
