### ISSUE TITLE
Icons not showing on Android 11

### ISSUE THREAD

**Issue by Civilian-No-001** [TacoTheDank/Scoop#11]
The saved trace icon does not follow the theme, the new icon is fine.

A11 auto dark theme
V2.1.3 Fdroid

**Comment by TacoTheDank** [comment]
I'm not quite sure what you mean. Could you provide a screenshot?

**Comment by Civilian-No-001** [comment]
Sorry, I have attached a screenshot now; and the icon may be black in dark mode.
![Pwe](https://user-images.githubusercontent.com/83265964/117338407-22dfff80-ae64-11eb-85d6-4c088a3cc3f7.png)

**Comment by TacoTheDank** [comment]
Hmm, it's likely this has to do with restrictions implemented on Android 11 (it shouldn't be showing the package names either). I'll need to look more into this.

**Comment by TacoTheDank** [comment]
@Civilian-No-001 Could you test the latest release (2.2.0) and see if this is still an issue (or if anything changed)? Thanks!

**Comment by TacoTheDank** [comment]
@Civilian-No-001 Any updates? I'd like to be able to close this issue if it's been fixed. I just need a confirmation that it now works for the newest version.

**Comment by kaozaza2** [comment]
No problem on 2.3.1

os: Android 11
device: Redmi Note 9S
rom: Pixel Experience Plus

![Screenshot_20210916-143243_Scoop](https://user-images.githubusercontent.com/11665930/133569853-2d2ee861-2dee-46c1-b05b-908b8cc99371.png)

**Comment by TacoTheDank** [comment]
I see... then I suppose this can be closed.

Fixed in https://github.com/TacoTheDank/Scoop/commit/c4c6f419d212e78e160ac0a68ef25445eb169aae.
