### ISSUE TITLE
Feature Request: update manager

### ISSUE THREAD

**Issue by mubashir-rehman** [TacoTheDank/Scoop#14]
Add a feature to check for updates on GitHub releases from with in the app.
If internet permission is a problem for some users or devs. Then a separate companion app would be a better option. Just like vanced manager.
However, if am update manager is to be considered for updating. Maybe, a separate universal project that updates apps from GitHub releases would be a better implementation. There might be something that already exists(like Aruora droid, fdroid) but many of such apps require apps or projects themselves to be listed. In contrast to that, I am suggesting to allow the user to pick/give a repository link and updates would be done on that basis(no need of varification period and other stuff).
Sorry for putting all thoughts in one issue.

**Comment by TacoTheDank** [comment]
It's fine. Ultimately though, I don't think this is necessary: the app exists on F-Droid, so you can update the app automatically that way. Also, adding an update checker would likely complicate the current co-existence on F-Droid, as I'd have to have separate builds and stuff for both APKs deployed on GitHub and F-Droid.

Thanks though!
