### ISSUE TITLE
(Question) ADB vs Xposed

### ISSUE THREAD

**Issue by NSTAdventure** [TacoTheDank/Scoop#18]
Which one is better?
Do xposed mode more accurate rather than ADB
@TacoTheDank

**Comment by TacoTheDank** [comment]
@NSTAdventure I don't really know, as I don't use Xposed personally. People wrote some reasons for supporting Xposed in [here](https://github.com/TacoTheDank/Scoop/issues/8). I re-integrated it as a result.
