### ISSUE TITLE
Start automatically at boot

### ISSUE THREAD

**Issue by Kreuger** [TacoTheDank/Scoop#19]
Hey man. I noticed that the app doesnt start automatically after restarting my phone and I often forget to do it. Could you add this in as an option?

**Comment by TacoTheDank** [comment]
Yes, I will attempt to tackle this :) Also, duplicate of https://github.com/TacoTheDank/Scoop/issues/4

**Comment by TacoTheDank** [comment]
🦀 It is crab-rave time 🦀 https://github.com/TacoTheDank/Scoop/pull/20
