### ISSUE TITLE
Scoop not showing storage permission

### ISSUE THREAD

**Issue by Gamemulatorer** [TacoTheDank/Scoop#22]
![Screenshot_2021-07-19-01-20-41-768_com google android permissioncontroller](https://user-images.githubusercontent.com/37603562/126076423-16fe19d1-0ccc-4844-b958-ff87a98f7e9b.jpg)
Android 10 MIUI 12.0.8
Redmi Note 9

**Comment by TacoTheDank** [comment]
...the app [does not request storage permissions](https://github.com/TacoTheDank/Scoop/blob/master/app/src/main/AndroidManifest.xml#L7) (nor does it require them)

**Comment by Gamemulatorer** [comment]
No description provided?
![Screenshot_2021-09-15-20-53-34](https://user-images.githubusercontent.com/37603562/133437092-7cc2726f-2efd-4a79-a895-4d9748cf9499.png)

**Comment by TacoTheDank** [comment]
@Gamemulatorer Someone made a PR that should fix this, I think. https://github.com/TacoTheDank/Scoop/pull/32
