### ISSUE TITLE
Stop button not working

### ISSUE THREAD

**Issue by ghost** [TacoTheDank/Scoop#25]
Pressing stop button on scoop notifications bar won't work they will do nothing and only way to stop is force stop the apps

Realme 5i
Android Q
Stock Rom
ADB Mode

Edit again:
I forgot if i downgrade the app recently 
Uh nvm 2.3.1 still not working :(

**Comment by Sidahmed-ben** [comment]
hello @TacoTheDank , i want to contribute on this project, do you agree that i solve this issue. Thank you 😉
