### ISSUE TITLE
Filter out duplicate crashlogs from the same app

### ISSUE THREAD

**Issue by uli-on** [TacoTheDank/Scoop#36]
... although the related setting is activated.
Or let's say "very much looks like", "very likely that...", cause I've not diffed the 38 crashes of current Floris Board beta04, god beware ;-)
(Edit: typo)

Scoop v2.3.1 (F-Droid)
Android 6.0.1 (with GMS upd. to 21.18.16, cn=M sdk=23)
Webview 94.0.4606.71
Motorola Moto G4
device not rooted

Not to forget: 

Huge thanks for making this app available!! Makes it soo much easier each time!!

**Comment by uli-on** [comment]
Sorry that I wasn't clear enough. What I meant is there are 38 crashes by Floris Board. When I tap the app name, all lines displayed read the same (at least the first two lines displayed there) and there are also 38 instances (counted by hand) of that same error. And although I know each of these error messages might differ by only one or two letters, it seems highly unlikely that all 38 would be unique errors, cause I've done the same several times with the Floris Board app. 
Also, I've observed that Scoop's behaviour on errors of more crashed apps. 

What I would expect is one list entry for one identical error, provided it is in fact exactly the same error, what I think *it is in fact*, cause — like I said — I've done the same several times with the Floris Board app (i.e. crash on start).

Was that any clearer, or would you still like to see a screenshot?

> Am 19.10.2021 um 23:02 schrieb Taco ***@***.***>:
> I, uh... could you provide a screenshot? I'm afraid I don't quite understand what you mean lol.

**Comment by TacoTheDank** [comment]
Reviewing how the app works, and Android limitations, I would have to say that this would be far too much work for not much benefit. I feel it should be up to the user to determine what to do with the crashlogs they get.

I think it would be easier for a user to delete the oldest crashlogs and keep the newest one. The issue with the newest order is something that I hope to tackle in a rewrite of the app.
