### ISSUE TITLE
Feature Request: Autostart Scoop on boot

### ISSUE THREAD

**Issue by srccrow** [TacoTheDank/Scoop#4]
If possible, I would like to ask feature to autostart app on boot with a switchable option, off by default.

**Comment by TacoTheDank** [comment]
Oh yes, absolutely. This is something I've considered adding for a while. I'm currently preparing to get Scoop on F-Droid first though. Thanks for the request!

**Comment by srccrow** [comment]
> Oh yes, absolutely. This is something I've considered adding for a while now. I'm currently preparing to get Scoop on F-Droid first though. Thanks for the request!

That is a very noble gesture from you, thanks!

**Comment by TacoTheDank** [comment]
@srccrow WOO
