### ISSUE TITLE
How to revoke READ_LOGS permission?

### ISSUE THREAD

**Issue by skyerjoe** [TacoTheDank/Scoop#43]
Which command in the adb shell revokes the given permisson for reading ?

**Comment by TacoTheDank** [comment]
`adb shell pm revoke taco.scoop android.permission.READ_LOGS`

May I ask why you would need to do so, though?

**Comment by skyerjoe** [comment]
Yes sure 
I want to deactivate this temporarily cause i dont need it everytime.

Further question  is there any history available which permissons are granted over adb ?

**Comment by TacoTheDank** [comment]
>Further question is there any history available which permissons are granted over adb ?

AFAIK, no.
