### ISSUE TITLE
Just wanted to ask, if I were to use bugjaegar app which command should I use?

### ISSUE THREAD

**Issue by Thewisem** [TacoTheDank/Scoop#7]
Just like the title says, I want to know the command needed for that to be activated. Bugjaegar is an app which when connected acts as a computer, I want to know the command needed to complete this.

**Comment by Thewisem** [comment]
When we connect devices it acts as a computer

**Comment by TacoTheDank** [comment]
Uhm, I don't know. I did some research into the tool, seems pretty cool. I imagine the command would be pretty similar.

I'll play around with it a bit and see if I can get it to grant the permission to another device. It probably can, I'll just have to test around a bit.

**Comment by Thewisem** [comment]
Thanks

**Comment by Thewisem** [comment]
So no answer

**Comment by TacoTheDank** [comment]
I haven't gotten around to it yet, I have other things I'm currently doing at the moment. This is not my top priority.

**Comment by Thewisem** [comment]
Uhhhhhh so got any answers?

**Comment by sudo-nautilus** [comment]
I've got an answer

**Comment by sudo-nautilus** [comment]
This should work in bugjaeger shell.

`pm grant taco.scoop android.permisssion.READ_LOGS`

**Comment by Thewisem** [comment]
Fun fact the version before this did not read any logs even though it started and when I crashed app it did not make it. But will try with the new one

**Comment by Thewisem** [comment]
And thanks

**Comment by sudo-nautilus** [comment]
Lmao :trollface:

**Comment by TacoTheDank** [comment]
@sudo-nautilus You typed one too many "s"s :flushed:

**Comment by sudo-nautilus** [comment]
@TacoTheDank lmao

**Comment by Thewisem** [comment]
Nice

**Comment by Thewisem** [comment]
And yeah btw problem solved. It works wonders

**Comment by Thewisem** [comment]
Probably should write this down in the documentation

**Comment by sudo-nautilus** [comment]
Oh lol

**Comment by sudo-nautilus** [comment]
@TacoTheDank 

> Fun fact the version before this did not read any logs even though it started and when I crashed app it did not make it. But will try with the new one

This is happening to so many users (including me lol) also, check your friend requests in Discord
