### ISSUE TITLE
Root permission not requested

### ISSUE THREAD

**Issue by Kreuger** [TacoTheDank/Scoop#9]
Hey I just found your app on fdroid. When I launch it I get the image "y u no allow root" but the app didnt request it. And I couldnt find a seting to manually trigger an attempt. I have a OnePlus Nord N10 5G on Android 10 with Magisk 22.1.

**Comment by TacoTheDank** [comment]
🤔 Interesting... I'll see what I can do about this.

**Comment by TacoTheDank** [comment]
Are you sure the app didn't request root? Other users have had it request fine. Is there a setting within your Magisk installation that could be preventing the dialog from appearing?

Thanks for opening an issue, btw :)

**Comment by Kreuger** [comment]
Im positive because it would show under Magisk as denied most likely since I didnt allow it. The only thing I could see possibly causing an issue is having biometric suppport on. But again, it would come up as denied root in Magisk.

**Comment by TacoTheDank** [comment]
@Kreuger Hmm, that's very strange that it doesn't even show up in the list.

I'll see about adding a prompt button to the "y u no allow root" page.

**Comment by Kreuger** [comment]
Cool thanks man.

**Comment by TacoTheDank** [comment]
@Kreuger I added some settings. See if they do the job :)

[scoop-release rootpref.zip](https://github.com/TacoTheDank/Scoop/files/6620677/scoop-release.rootpref.zip)

Commit so you can see the changes: https://github.com/TacoTheDank/Scoop/commit/4d2fddc210bf6ceb805d72cb15691737e1201afa

Might as well do some testing too. Could you tell me if the permission status setting summary changes when (or I guess if) root is granted and you restart the app? That mean taking note of it saying "READ_LOGS permission is denied" first, and then it changing to "READ_LOGS permission is granted." Thanks!

**Comment by Kreuger** [comment]
Thanks for working on this. Tapping the button to request root manually doesnt seem to do anything. No toast notification and it didnt request root from what I can tell.

**Comment by TacoTheDank** [comment]
> Thanks for working on this. Tapping the button to request root manually doesnt seem to do anything. No toast notification and it didnt request root from what I can tell.
> 
> Edit: I figured it out! In Magisk I had to "reset" the app because I had used the setting to hide it from apps looking for it. As soon as I opened Scoop after that, the toast requesting root came up and I didnt need to try manually.

Lol I had a feeling it had to do with Magisk. The settings I added launched the same commands as the app did on startup, so I figured it probably wouldn't have actually helped. Thanks for figuring it out!
